coverage:
  status:
    project:
      default:
        # Basic settings
        target: 90%
        threshold: 1%
    patch:
      default:
        # Coverage target for PR changes
        target: 95%
        threshold: 1%

# Ignore patterns
ignore:
  - "tests/**/*"
  - "setup.py"
  - "docs/**/*"

# Configure PR comments
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Only post if coverage changes
  require_base: yes
  require_head: yes 